### ISSUE TITLE
do we still need this?

### ISSUE THREAD

**Issue by dominictarr** [ssb-junkyard/ssb-server-plugins#1]
I think we have https://github.com/ssbc/ssb-plugins so we can just delete this?

**Comment by dominictarr** [comment]
@christianbundy

**Comment by christianbundy** [comment]
Is ssb-plugins the same thing? I thought that was ssb-plugins2 or something.

**Comment by dominictarr** [comment]
yeah, merged ssb-plugins2 and ssb-plugins are merged now.
